### ISSUE TITLE
exit code getting swallowed when running in CI

### ISSUE THREAD

**Issue by bucko13** [bcoin-org/bmocha#3]
Even though a test has failed and `process.exit` is run with `1`, CircleCI is still exiting with a code of `0`. It seems like the error code is getting swallowed somewhere. Tried running with mocha and it fails as expected.

**Comment by bucko13** [comment]
Not sure if it's related, but I passed the `--exit` argument and it just seemed to skip all tests

**Comment by chjj** [comment]
Hmm, seems to be working on my machine:

```
$ bmocha test/sanity-test.js || echo 1

  Mocha 1                                                                                                                                                
     should succeed                                                                                                                                     
     should fail (randomly)                                                                                                                             
     should take a while (1) (42ms)                                                                                                                     
     should take a while (2) (131ms)                                                                                                                    
     should take a while (3)                                                                                                                            
     should happen before describe                                                                                                                      
    Mocha 2                                                                                                                                              
       should succeed                                                                                                                                   
      1) should fail (randomly)                                                                                                                          
                                                                                                                                                         
  Mocha 3                                                                                                                                                
    - should skip                                                                                                                                        
     should not skip                                                                                                                                    
                                                                                                                                                         
  8 passing (1s)
  1 pending
  1 failing

  1) Mocha 2
      should fail (randomly):

      AssertionError [ERR_ASSERTION]: strictEqual failed.

      Expected values to be strictly equal:
      
      0 !== 1
      

      at Context.it (/home/chjj/work/node_modules/bmocha/test/sanity-test.js:72:16)
      at Promise (/home/chjj/work/node_modules/bmocha/lib/bmocha.js:418:30)
      at new Promise (<anonymous>)
      at Test.exec (/home/chjj/work/node_modules/bmocha/lib/bmocha.js:402:12)
      at Test.run (/home/chjj/work/node_modules/bmocha/lib/bmocha.js:459:20)
      at Suite.exec (/home/chjj/work/node_modules/bmocha/lib/bmocha.js:336:23)

1
```

**Comment by braydonf** [comment]
Everything is working, see https://github.com/bcoin-org/bcoin/pull/651

**Comment by bucko13** [comment]
Ah ok, thanks for the sanity checks! I figured out what was going. Running the test as in the JS example in the readme, i.e. actually importing `bmocha` into the file and then running a script as `bmocha --reporter spec test` exits as expected with a code of `1` locally and reports the errors properly. However, on CircleCI it says the test passed even though the console output reports the failed test (see test on CircleCI [here](https://circleci.com/gh/bpanel-org/connection-manager/68?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)). Calling the example code as a node script though (e.g. `node test/my-test.js`) fails on CircleCI as expected. 

So removing the `const code = await mocha.run(() => { ... })` and just replacing `mocha` with `bmocha` in an npm script will report as expected.
